In [9]:
import pandas as pd

In [10]:
df = pd.read_csv('pso_resultsMP.csv')
df

,function,swarmsize,dim,maxiter,w,c1,c2,duration,best_iter,best_val,best_pos
0,quadratic,100,2,60,0.4,1.0,1.0,0.006628,60,2.347920e-25,-3.68043e-13;3.15176e-13
1,quadratic,100,2,60,0.4,1.0,1.3,0.000646,60,2.162800e-24,-1.45395e-12;-2.21003e-13
2,quadratic,100,2,60,0.4,1.0,1.5,0.000650,60,7.701520e-23,8.38333e-12;-2.59519e-12
3,quadratic,100,2,60,0.4,1.0,1.7,0.000678,60,4.142310e-21,2.67406e-11;-5.85427e-11
4,quadratic,100,2,60,0.4,1.0,2.0,0.000422,60,5.065090e-20,-1.87067e-10;-1.25127e-10
...,...,...,...,...,...,...,...,...,...,...,...
46870,ackley,2000,15,1000,1.0,2.0,1.0,0.359129,32,3.533210e+00,0.394556;-0.348887;0.352099;0.687693;-0.008102...
46871,ackley,2000,15,1000,1.0,2.0,1.3,0.366825,48,4.090680e+00,0.422115;0.59564;-0.370652;0.56327;1.65049;-0....
46872,ackley,2000,15,1000,1.0,2.0,1.5,0.364981,86,4.903750e+00,-0.221191;0.382834;-0.459122;0.977323;-1.79466...
46873,ackley,2000,15,1000,1.0,2.0,1.7,0.409998,117,4.986970e+00,-0.118086;-1.63044;-0.107625;-0.636742;-0.2857...
46874,ackley,2000,15,1000,1.0,2.0,2.0,0.381143,240,5.666310e+00,-0.550286;0.235352;-0.41709;2.77841;1.11883;-1...